version: '3.8'
services:
  player_dev_db:
    image: postgres:14
    container_name: player_dev_db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - player

volumes:
  postgres:
    name: player

networks:
  player: